apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: common
  name: {{ .Values.name }}-common
  namespace: argocd
spec:
  destination:
    name: {{ .Values.name }}
    namespace: common
  project: default
  source:
    path: manifests
    repoURL: https://github.com/larkintuckerllc/common-app
    targetRevision: {{ if or (eq .Values.environment "testing") (eq .Values.region "region-1") }}0.3.0{{ else }}0.2.1{{ end }}
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
