apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: environment
  name: "{{ .Values.name }}-environment"
  namespace: argocd
spec:
  destination:
    name: "{{ .Values.name }}"
    namespace: environment
  project: default
  source:
    path: "manifests/overlays/{{ .Values.environment }}"
    repoURL: https://github.com/larkintuckerllc/environment-app
    targetRevision: 0.1.1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
  